services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: homesync_pass
      POSTGRES_USER: homesync_user
      POSTGRES_DB: homesync_dev
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:   